[openssl]
source = 'git'
git = 'https://github.com/openssl/openssl.git'
prefix = 'openssl-'
include_regex = 'openssl-[0-9]+\.[0-9]+\.[0-9]+'

#source = "regex"
#url = "https://openssl-library.org/source/index.html"
#regex = "openssl-(\\d+\\.\\d+\\.\\d+).tar.gz"
