version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "distribution.ini",
    "mozconfig.cfg",
    "vendor-prefs.js",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-cargo-.gitmodules.patch",
    "metainfo.patch",
]
SPDX-FileCopyrightText = "thunderbird contributors"
SPDX-License-Identifier = "MPL-2.0"
