[hplip]
source = "regex"
# source = "httpheader"
# regex = "The current version of the HPLIP solution is version (\\d+.\\d+.\\d+)"
# url = "https://developers.hp.com/hp-linux-imaging-and-printing/"
# url = "https://developels.hp.com/hp-linux-imaging-and-printing/gethplip"
# url = "https://developers.hp.com/hp-linux-imaging-and-printing/release_notes"
regex = "hplip-(\\d+.\\d+.\\d+).tar.gz"
url = "https://sourceforge.net/projects/hplip/"
