version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0003-models.dat-Re-add-drivers-missing-from-3.19.1.patch",
    "0018-Allow-non-JPEG-scanning-on-the-HP-DeskJet-3520-All-i.patch",
    "0022-Add-include-cups-ppd.h-in-various-places-as-CUPS-2.2.patch",
    "0023-Fix-handling-of-unicode-filenames-in-sixext.py.patch",
    "disable_upgrade.patch",
    "hplip-1_3_23_12-4-python3_12-fix.patch",
    "hplip-configure-python.patch",
    "hplip-hpaio-gcc14.patch",
    "hplip-locale-format.patch",
    "hplip-pserror-gcc14.patch",
    "reproducible-gzip.patch",
    "python3.diff",
    "hplip-gcc15-stdc23.patch",
    "hplip-no-urlopener.patch",
]
SPDX-FileCopyrightText = "hplip contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
