version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "mupdf-1.23.9-cpp_ldflags.patch",
    "mupdf-1.23.9-install_targets.patch",
]
SPDX-FileCopyrightText = "mupdf contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
