[mysql-workbench]
source = "regex"
url = "https://dev.mysql.com/downloads/workbench/?tpl=files&os=src&osva=All%20Operating%20Systems%20(Generic)%20(Architecture%20Independent)"
regex = "mysql-workbench-community-([0-9\\.]+)-src.tar.gz"
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"
