version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "libreoffice-fresh.csh",
    "libreoffice-fresh.sh",
    "soffice-template.desktop.in",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix_build_with_poppler_26.01.0.patch",
    "libreoffice-24.8.4.2-icu76_fixes-1.patch",
    "mdds-3.0.0.patch",
    "orcus-0.21.0.patch",
]
SPDX-FileCopyrightText = "libreoffice-fresh contributors"
SPDX-License-Identifier = "MPL-2.0 AND LGPL-3.0-or-later"
