version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "lib32-glibc.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "locale-gen",
    "locale.gen.txt",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
    "sdt.h",
    "sdt-config.h",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "CC0-1.0"
